version: '3'
services:
  mongodb:
    image: mongo:3.6.1
    container_name: mongo
    ports:
      - "27017:27017"
   
    command: 'mongod'

  roundrobin:
    image: roundrobin
    ports:
      - "4567:4567"
    container_name: roundrobin
    

  service1:
    image: service
    ports:
      - "4568:4568"
    container_name: service1
    

  service2:
    image: service
    ports:
      - "4569:4568"
    container_name: service2
   

  service3:
    image: service
    ports:
      - "4570:4568"
    container_name: service3
   

